import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
import Header from "@/components/Header/Header";
import NextAuthProvider from "@/components/NextAuthProvider/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			<body className={inter.className}>
				<NextAuthProvider>
					<TooltipProvider>
						<div className="flex flex-col sm:flex-row h-screen w-screen overflow-hidden">
							<Header />
							<main className="flex-1 p-6 min-h-screen overflow-auto">
								{children}
							</main>
						</div>
					</TooltipProvider>
					<Toaster />
				</NextAuthProvider>
			</body>
		</html>
	);
}
